CERTS	:= ../certs

test:
	pubsub -v --ca ca.crt --cert test.crt --key test.key --host aqyn60mvlikb9-ats.iot.ap-southeast-2.amazonaws.com --client sdk-nodejs-23a34f7c-7e1c-4c91-a60f-c36f4dddd168 --topic topic_2
